version: '3'

services: 
  bot:
    image: meaty/botapi
    build: .
    ports:
      - 5000
    depends_on: 
      - nginx
  nginx:
    image: nginx:latest 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports: 
      - 8080:8080
   